---
- import_tasks: include-vars.yml

- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and not certbot_skip_installation|bool

- import_tasks: install-with-package.yml
  when: certbot_install_method == 'package' and not certbot_skip_installation|bool

- import_tasks: install-with-snap.yml
  when: certbot_install_method == 'snap' and not certbot_skip_installation|bool

- import_tasks: install-from-source.yml
  when: certbot_install_method == 'source' and not certbot_skip_installation|bool

- include_tasks: create-cert-standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- include_tasks: create-cert-webroot.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'webroot'
  loop_control:
    loop_var: cert_item

- import_tasks: renew-cron.yml
  when: certbot_auto_renew
